# Generated by Django 4.2 on 2023-04-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_statusitem_crop_type_statusitem_is_sprinkler_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusitem',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
